# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w
        -X github.com/nikhilsbhat/opensource-insight-exporter/version.Version={{.Version}}
        -X github.com/nikhilsbhat/opensource-insight-exporter/version.Env={{.Env.BUILD_ENVIRONMENT}}
        -X github.com/nikhilsbhat/opensource-insight-exporter/version.BuildDate={{.Date}}
        -X github.com/nikhilsbhat/opensource-insight-exporter/version.Revision={{.Commit}}
        -X github.com/nikhilsbhat/opensource-insight-exporter/version.GoVersion={{.Env.GOVERSION}}
        -X github.com/nikhilsbhat/opensource-insight-exporter/version.Platform={{ .Os }}/{{ .Arch }}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    binary: '{{ .ProjectName }}'

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - opensource-insight-exporter
    skip_push: false
    image_templates:
      - "basnik/opensource-insight-exporter:latest"
      - "basnik/opensource-insight-exporter:{{ .Tag }}"
      - "basnik/opensource-insight-exporter:{{ .Tag }}-{{ .Env.GOVERSION }}"
    dockerfile: Dockerfile

archives:
  - format: 'tar.gz'
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
      name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
