scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: opensource-insight-exporter
    scrape_interval: 120s
    static_configs:
      - targets:
        - "192.168.0.100:8090"
